name: Docker
on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [main]
jobs:
  push-images:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: yanncarvalho
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: ./
        file: Dockerfile
        push: true
        tags: |
          yanncarvalho/perfect-match:latest
          yanncarvalho/perfect-match:${{ github.sha }}
